// Generates projects/ng-core-ui/styles/_logos.scss
// by embedding logo files as data URIs so consuming apps don't need to serve
// the assets separately. Must run BEFORE ng-packagr so the SCSS is picked up.
//
// SVG logos: URL-encoded (more compact, human-readable)
// PNG logos:  base64-encoded

import { readFileSync, writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const libDir = resolve(__dirname, '../projects/ng-core-ui');

function svgToDataUri(filePath) {
  const data = readFileSync(filePath);
  return `data:image/svg+xml;base64,${data.toString('base64')}`;
}

function pngToDataUri(filePath) {
  const data = readFileSync(filePath);
  return `data:image/png;base64,${data.toString('base64')}`;
}

const themes = [
  {
    varName: 'gpa',
    file: resolve(libDir, 'assets/themes/logos/gpa.svg'),
    encode: svgToDataUri,
  },
  {
    varName: 'poste',
    file: resolve(libDir, 'assets/themes/logos/poste.png'),
    encode: pngToDataUri,
  },
];

const lines = [
  '// AUTO-GENERATED by scripts/embed-logos.mjs — do not edit manually.',
  "// Run 'npm run build:embed-logos' to regenerate after changing a logo file.",
  '',
];

for (const { varName, file, encode } of themes) {
  const uri = encode(file);
  lines.push(`$${varName}: '${uri}';`);
  console.log(`✔ Embedded ${varName} logo (${file.split('/').pop()})`);
}

lines.push('');

const outputPath = resolve(libDir, 'styles/_logos.scss');
writeFileSync(outputPath, lines.join('\n'));
console.log('✔ Generated projects/ng-core-ui/styles/_logos.scss');
